version: "3.7"
services:
  db:
    image: mysql:5.7
    container_name: mysql-Projeto
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: meubanco
    ports:
      - "3306:3306"
    volumes:
      - dados:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - minha-rede
volumes:
  dados:
networks:
  minha-rede:
    driver: bridge